witnesses = [
  {
    address = "TWxhM3gR8A8tyMqCU6Z4bJzdBQLCBe25Bs"
    url = "http://meme5.com"
    voteCount = 100000036
  },
  {
    address = "TPL66VK2gCXNCD7EJg9pgJRfqcRazjhUZY"
    voteCount = 100000035
  },
  {
    address = "TCjptjyjenNKB2Y6EwyVT43DQyUUorxKWi"
    voteCount = 100000034
  }
]

accounts = [
  {
    address = "TWxhM3gR8A8tyMqCU6Z4bJzdBQLCBe25Bs"
    accountName = "Normal"
    balance = 99000000000000000
  },
  {
    address = "TPL66VK2gCXNCD7EJg9pgJRfqcRazjhUZY"
    accountType = "Normal"
    balance = 98000000000000000
  },
  {
    address = "TCjptjyjenNKB2Y6EwyVT43DQyUUorxKWi"
    accountType = "Normal"
    balance = 97000000000000000
  }
]
