witnesses = [
  {
    address = "TWxhM3gR8A8tyMqCU6Z4bJzdBQLCBe25Bs"
    url = "http://meme5.com"
    voteCount = 100000036
  },
  {
    address = "TPL66VK2gCXNCD7EJg9pgJRfqcRazjhUZY"
    voteCount = 100000035
  }
]

accounts = [
  {
    address = "TWxhM3gR8A8tyMqCU6Z4bJzdBQLCBe25Bs"
    accountName = "TWxhM"
    balance = 99000000000000000
  },
  {
    address = "TPL66VK2gCXNCD7EJg9pgJRfqcRazjhUZY"
    accountType = "TPL66"
    balance = 98000000000000000
  },
  {
    address = "TCjptjyjenNKB2Y6EwyVT43DQyUUorxKWi"
    accountType = "TCjpt"
    balance = 97000000000000000
  }
]

latestBlockHeaderTimestamp = 1758087563000
