        
#!/bin/bash
# TRON Java Environment Configuration
# Generated by install_dependencies.sh on Thu Jan 22 15:27:00 +08 2026

export JAVA_HOME="/opt/homebrew/opt/openjdk@17"
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"

echo "Java environment configured:"
echo "   JAVA_HOME: $JAVA_HOME"
echo "   Java version: $(java -version 2>&1 | head -n 1)"
