package org.tron.core.db;

import java.util.List;
import org.tron.common.runtime.Runtime;
import org.tron.common.utils.Sha256Hash;
import org.tron.core.capsule.AccountCapsule;
import org.tron.core.capsule.ReceiptCapsule;
import org.tron.core.capsule.TransactionCapsule;
import org.tron.core.exception.ContractExeException;
import org.tron.core.exception.ContractValidateException;
import org.tron.core.exception.ReceiptException;
import org.tron.protos.Protocol.Transaction.Contract;

public class TransactionTrace {

  private TransactionCapsule trx;

  private ReceiptCapsule receipt;

  private Manager dbManager;

  AccountCapsule owner;

  public TransactionCapsule getTrx() {
    return trx;
  }

  public TransactionTrace(TransactionCapsule trx, Manager dbManager) {
    this.trx = trx;
    this.dbManager = dbManager;
    this.owner = dbManager.getAccountStore()
        .get(TransactionCapsule.getOwner(trx.getInstance().getRawData().getContract(0)));
    this.receipt = new ReceiptCapsule(Sha256Hash.ZERO_HASH);

  }

  //pre transaction check
  public void init() throws ContractValidateException {
    List<Contract> contractList = trx.getInstance().getRawData().getContractList();
    long castMaxTrx = 0;
    for (Contract contract : contractList) {
//      castMaxTrx = Math.addExact(castMaxTrx, TransactionCapsule.getCpuLimitInTrx(contract));
//      castMaxTrx = Math.addExact(castMaxTrx, TransactionCapsule.getStorageLimitInTrx(contract));
//      castMaxTrx = Math.addExact(castMaxTrx, TransactionCapsule.getCallValue(contract));
    }
    if (owner.getBalance() < castMaxTrx) {
      throw new ContractValidateException(
          "init trace error, balance is not sufficient.");
    }
//    receipt.payCpuBill();
    checkStorage();
  }

  //set bill
  public void setBill(long cpuUseage, long storageUseage) {
    receipt.setCpuUsage(cpuUseage);
    receipt.setStorageDelta(storageUseage);
  }


  private void checkStorage() {
    //TODO if not enough buy some storage auto
    receipt.buyStorage(0);
  }

  public void exec(Runtime runtime) throws ContractExeException, ContractValidateException {
    /**  VM execute  **/
    runtime.init();
    runtime.execute();
    runtime.go();
  }

  public void finalize() {
    //TODO: if SR package this this trx, use their receipt
    ReceiptCapsule witReceipt = new ReceiptCapsule(trx.getInstance().getRet(0).getReceipt(),
        trx.getTransactionId());
    //TODO calculatedly pay cpu pay storage
    receipt.payCpuBill();
    receipt.payStorageBill();
    //TODO: pay bill
  }

  /**
   * checkBill checked if the receipt of the SR is equal to the receipt generated by the TVM.
   */
  public void checkBill() throws ReceiptException {
    ReceiptCapsule srReceipt = new ReceiptCapsule(this.trx.getInstance().getRet(0).getReceipt(),
        this.trx.getTransactionId());

//    if ((this.receipt.getStorageFee() != srReceipt.getStorageFee())
//        || (this.receipt.getStorageDelta() != srReceipt.getStorageDelta())) {
//      throw new ReceiptException(
//          "Check bill exception, storage delta or fee not equal, current storage delta: "
//              + this.receipt.getStorageDelta()
//              + ", target storage delta: "
//              + srReceipt.getStorageDelta()
//              + ", current storage fee: "
//              + this.receipt.getStorageFee()
//              + ", target storage fee: "
//              + srReceipt.getStorageFee());
//    }

//    long adjustedCpuFee = Math.abs(this.receipt.getCpuFee() - this.receipt.getCpuFee());
//    long adjustedCpuUsage = Math.abs(this.receipt.getCpuUsage() - this.receipt.getCpuUsage());
//
//    double cpuFeePercent = adjustedCpuFee * 1.0 / srReceipt.getCpuFee() * 100;
//    double cpuUsagePercent = adjustedCpuUsage * 1.0 / srReceipt.getCpuUsage()  * 100;
//
//    double percentRange = 30;
//    if ((cpuFeePercent > percentRange) || (cpuUsagePercent > percentRange)) {
//      throw new ReceiptException(
//          "Check bill exception, cpu usage or fee not equal(percent <="
//              + percentRange
//              + "%), current cpu usage: "
//              + this.receipt.getCpuUsage()
//              + ", target cpu usage: "
//              + srReceipt.getCpuUsage()
//              + ", current cpu fee: "
//              + this.receipt.getCpuFee()
//              + ", target cpu fee: "
//              + srReceipt.getCpuFee()
//              + ", cpu usage percent: "
//              + cpuUsagePercent
//              + "%, cpu fee percent: "
//              + cpuFeePercent + "%");
//    }

    this.receipt.setReceipt(ReceiptCapsule.copyReceipt(srReceipt));
  }

}
