package org.tron.core.config.args;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;

import java.io.File;
import java.security.SecureRandom;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.ClassRule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.tron.common.crypto.SignInterface;
import org.tron.common.crypto.SignUtils;
import org.tron.common.utils.ByteArray;
import org.tron.common.utils.LocalWitnesses;
import org.tron.keystore.Credentials;
import org.tron.keystore.WalletUtils;

/**
 * Backward compatibility: verifies that keystore files generated by
 * the new Toolkit code path can be loaded by WitnessInitializer
 * (used by FullNode at startup via localwitnesskeystore config).
 */
public class WitnessInitializerKeystoreTest {

  @ClassRule
  public static final TemporaryFolder tempFolder = new TemporaryFolder();

  // WitnessInitializer prepends user.dir to the filename, so we must
  // create the keystore dir relative to user.dir. Use unique name to
  // avoid collisions with parallel test runs.
  private static final String DIR_NAME =
      ".test-keystore-" + System.currentTimeMillis();

  private static String keystoreFileName;
  private static String expectedPrivateKey;
  private static final String PASSWORD = "backcompat123";

  @BeforeClass
  public static void setUp() throws Exception {
    Args.setParam(new String[]{"-d", tempFolder.newFolder().toString()},
        "config-test.conf");

    SignInterface keyPair = SignUtils.getGeneratedRandomSign(
        SecureRandom.getInstance("NativePRNG"), true);
    expectedPrivateKey = ByteArray.toHexString(keyPair.getPrivateKey());

    File dir = new File(System.getProperty("user.dir"), DIR_NAME);
    dir.mkdirs();
    String generatedName =
        WalletUtils.generateWalletFile(PASSWORD, keyPair, dir, true);
    keystoreFileName = DIR_NAME + "/" + generatedName;
  }

  @AfterClass
  public static void tearDown() {
    Args.clearParam();
    File dir = new File(System.getProperty("user.dir"), DIR_NAME);
    if (dir.exists()) {
      File[] files = dir.listFiles();
      if (files != null) {
        for (File f : files) {
          f.delete();
        }
      }
      dir.delete();
    }
  }

  @Test
  public void testNewKeystoreLoadableByWitnessInitializer() {
    java.util.List<String> keystores =
        java.util.Collections.singletonList(keystoreFileName);

    LocalWitnesses result = WitnessInitializer.initFromKeystore(
        keystores, PASSWORD, null);

    assertNotNull("WitnessInitializer should load new keystore", result);
    assertFalse("Should have at least one private key",
        result.getPrivateKeys().isEmpty());
    assertEquals("Private key must match original",
        expectedPrivateKey, result.getPrivateKeys().get(0));
  }
}
