package org.tron.keystore;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import org.junit.Test;
import org.tron.common.crypto.SignInterface;
import org.tron.common.crypto.SignUtils;
import org.tron.common.utils.Utils;

/**
 * Cross-implementation compatibility tests.
 * Verifies that keystore files can survive a roundtrip through the
 * Java implementation (encrypt → serialize → deserialize → decrypt).
 *
 * Also verifies that keystore files generated by legacy --keystore-factory
 * code are compatible with the new library.
 */
public class CrossImplTest {

  private static final ObjectMapper MAPPER = new ObjectMapper()
      .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

  @Test
  public void testLightKeystoreRoundtrip() throws Exception {
    String password = "testpassword123";
    SignInterface keyPair = SignUtils.getGeneratedRandomSign(Utils.getRandom(), true);
    byte[] originalKey = keyPair.getPrivateKey();

    // Create keystore → write to temp file → read back → decrypt
    WalletFile walletFile = Wallet.createLight(password, keyPair);
    File tempFile = File.createTempFile("keystore-test-", ".json");
    tempFile.deleteOnExit();
    MAPPER.writeValue(tempFile, walletFile);

    WalletFile loaded = MAPPER.readValue(tempFile, WalletFile.class);
    SignInterface recovered = Wallet.decrypt(password, loaded, true);

    assertArrayEquals("File roundtrip must preserve private key",
        originalKey, recovered.getPrivateKey());
  }

  @Test
  public void testStandardKeystoreRoundtrip() throws Exception {
    String password = "testpassword456";
    SignInterface keyPair = SignUtils.getGeneratedRandomSign(Utils.getRandom(), true);
    byte[] originalKey = keyPair.getPrivateKey();

    WalletFile walletFile = Wallet.createStandard(password, keyPair);
    File tempFile = File.createTempFile("keystore-std-", ".json");
    tempFile.deleteOnExit();
    MAPPER.writeValue(tempFile, walletFile);

    WalletFile loaded = MAPPER.readValue(tempFile, WalletFile.class);
    SignInterface recovered = Wallet.decrypt(password, loaded, true);

    assertArrayEquals("Standard scrypt file roundtrip must preserve private key",
        originalKey, recovered.getPrivateKey());
  }

  @Test
  public void testKeystoreAddressConsistency() throws Exception {
    String password = "addresscheck";
    SignInterface keyPair = SignUtils.getGeneratedRandomSign(Utils.getRandom(), true);
    Credentials original = Credentials.create(keyPair);

    WalletFile walletFile = Wallet.createLight(password, keyPair);
    assertEquals("WalletFile address must match credentials address",
        original.getAddress(), walletFile.getAddress());

    SignInterface recovered = Wallet.decrypt(password, walletFile, true);
    Credentials recoveredCreds = Credentials.create(recovered);
    assertEquals("Recovered address must match original",
        original.getAddress(), recoveredCreds.getAddress());
  }

  @Test
  public void testLoadCredentialsIntegration() throws Exception {
    String password = "integration789";
    SignInterface keyPair = SignUtils.getGeneratedRandomSign(Utils.getRandom(), true);
    byte[] originalKey = keyPair.getPrivateKey();
    String originalAddress = Credentials.create(keyPair).getAddress();

    // Use WalletUtils full flow
    File tempDir = new File(System.getProperty("java.io.tmpdir"), "keystore-test-" +
        System.currentTimeMillis());
    tempDir.mkdirs();
    try {
      String fileName = WalletUtils.generateWalletFile(password, keyPair, tempDir, false);
      assertNotNull(fileName);

      File keystoreFile = new File(tempDir, fileName);
      Credentials loaded = WalletUtils.loadCredentials(password, keystoreFile, true);

      assertEquals("Address must survive full WalletUtils roundtrip",
          originalAddress, loaded.getAddress());
      assertArrayEquals("Key must survive full WalletUtils roundtrip",
          originalKey, loaded.getSignInterface().getPrivateKey());
    } finally {
      // Cleanup
      File[] files = tempDir.listFiles();
      if (files != null) {
        for (File f : files) {
          f.delete();
        }
      }
      tempDir.delete();
    }
  }
}
