// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/TronTXOutputs.proto

package org.tron.protos.core;

public final class TronTXOutputs {
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_protos_TXOutputs_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_TXOutputs_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
        "\n\030core/TronTXOutputs.proto\022\006protos\032\027core" +
            "/TronTXOutput.proto\".\n\tTXOutputs\022!\n\007outp" +
            "uts\030\001 \003(\0132\020.protos.TXOutputB%\n\024org.tron." +
            "protos.coreB\rTronTXOutputsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
                org.tron.protos.core.TronTXOutput.getDescriptor(),
            }, assigner);
    internal_static_protos_TXOutputs_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_protos_TXOutputs_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_TXOutputs_descriptor,
        new java.lang.String[] {"Outputs",});
    org.tron.protos.core.TronTXOutput.getDescriptor();
  }

  private TronTXOutputs() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  public interface TXOutputsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.TXOutputs)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protos.TXOutput outputs = 1;</code>
     */
    java.util.List<org.tron.protos.core.TronTXOutput.TXOutput>
    getOutputsList();

    /**
     * <code>repeated .protos.TXOutput outputs = 1;</code>
     */
    org.tron.protos.core.TronTXOutput.TXOutput getOutputs(int index);

    /**
     * <code>repeated .protos.TXOutput outputs = 1;</code>
     */
    int getOutputsCount();

    /**
     * <code>repeated .protos.TXOutput outputs = 1;</code>
     */
    java.util.List<? extends org.tron.protos.core.TronTXOutput.TXOutputOrBuilder>
    getOutputsOrBuilderList();

    /**
     * <code>repeated .protos.TXOutput outputs = 1;</code>
     */
    org.tron.protos.core.TronTXOutput.TXOutputOrBuilder getOutputsOrBuilder(
        int index);
  }

  /**
   * Protobuf type {@code protos.TXOutputs}
   */
  public static final class TXOutputs extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.TXOutputs)
      TXOutputsOrBuilder {
    public static final int OUTPUTS_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:protos.TXOutputs)
    private static final org.tron.protos.core.TronTXOutputs.TXOutputs DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<TXOutputs>
        PARSER = new com.google.protobuf.AbstractParser<TXOutputs>() {
      public TXOutputs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TXOutputs(input, extensionRegistry);
      }
    };

    static {
      DEFAULT_INSTANCE = new org.tron.protos.core.TronTXOutputs.TXOutputs();
    }

    private java.util.List<org.tron.protos.core.TronTXOutput.TXOutput> outputs_;
    private byte memoizedIsInitialized = -1;

    // Use TXOutputs.newBuilder() to construct.
    private TXOutputs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private TXOutputs() {
      outputs_ = java.util.Collections.emptyList();
    }

    private TXOutputs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                outputs_ = new java.util.ArrayList<org.tron.protos.core.TronTXOutput.TXOutput>();
                mutable_bitField0_ |= 0x00000001;
              }
              outputs_.add(
                  input.readMessage(org.tron.protos.core.TronTXOutput.TXOutput.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          outputs_ = java.util.Collections.unmodifiableList(outputs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return org.tron.protos.core.TronTXOutputs.internal_static_protos_TXOutputs_descriptor;
    }

    public static org.tron.protos.core.TronTXOutputs.TXOutputs parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.tron.protos.core.TronTXOutputs.TXOutputs parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tron.protos.core.TronTXOutputs.TXOutputs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.tron.protos.core.TronTXOutputs.TXOutputs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tron.protos.core.TronTXOutputs.TXOutputs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.tron.protos.core.TronTXOutputs.TXOutputs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tron.protos.core.TronTXOutputs.TXOutputs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static org.tron.protos.core.TronTXOutputs.TXOutputs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.tron.protos.core.TronTXOutputs.TXOutputs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.tron.protos.core.TronTXOutputs.TXOutputs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.tron.protos.core.TronTXOutputs.TXOutputs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static org.tron.protos.core.TronTXOutputs.TXOutputs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.tron.protos.core.TronTXOutputs.TXOutputs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static org.tron.protos.core.TronTXOutputs.TXOutputs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<TXOutputs> parser() {
      return PARSER;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return org.tron.protos.core.TronTXOutputs.internal_static_protos_TXOutputs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tron.protos.core.TronTXOutputs.TXOutputs.class, org.tron.protos.core.TronTXOutputs.TXOutputs.Builder.class);
    }

    /**
     * <code>repeated .protos.TXOutput outputs = 1;</code>
     */
    public java.util.List<org.tron.protos.core.TronTXOutput.TXOutput> getOutputsList() {
      return outputs_;
    }

    /**
     * <code>repeated .protos.TXOutput outputs = 1;</code>
     */
    public java.util.List<? extends org.tron.protos.core.TronTXOutput.TXOutputOrBuilder>
    getOutputsOrBuilderList() {
      return outputs_;
    }

    /**
     * <code>repeated .protos.TXOutput outputs = 1;</code>
     */
    public int getOutputsCount() {
      return outputs_.size();
    }

    /**
     * <code>repeated .protos.TXOutput outputs = 1;</code>
     */
    public org.tron.protos.core.TronTXOutput.TXOutput getOutputs(int index) {
      return outputs_.get(index);
    }

    /**
     * <code>repeated .protos.TXOutput outputs = 1;</code>
     */
    public org.tron.protos.core.TronTXOutput.TXOutputOrBuilder getOutputsOrBuilder(
        int index) {
      return outputs_.get(index);
    }

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      for (int i = 0; i < outputs_.size(); i++) {
        output.writeMessage(1, outputs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
        return size;
      }

      size = 0;
      for (int i = 0; i < outputs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, outputs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof org.tron.protos.core.TronTXOutputs.TXOutputs)) {
        return super.equals(obj);
      }
      org.tron.protos.core.TronTXOutputs.TXOutputs other = (org.tron.protos.core.TronTXOutputs.TXOutputs) obj;

      boolean result = true;
      result = result && getOutputsList()
          .equals(other.getOutputsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getOutputsCount() > 0) {
        hash = (37 * hash) + OUTPUTS_FIELD_NUMBER;
        hash = (53 * hash) + getOutputsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TXOutputs> getParserForType() {
      return PARSER;
    }

    public org.tron.protos.core.TronTXOutputs.TXOutputs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code protos.TXOutputs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.TXOutputs)
        org.tron.protos.core.TronTXOutputs.TXOutputsOrBuilder {
      private int bitField0_;
      private java.util.List<org.tron.protos.core.TronTXOutput.TXOutput> outputs_ =
          java.util.Collections.emptyList();
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.tron.protos.core.TronTXOutput.TXOutput, org.tron.protos.core.TronTXOutput.TXOutput.Builder, org.tron.protos.core.TronTXOutput.TXOutputOrBuilder> outputsBuilder_;

      // Construct using org.tron.protos.core.TronTXOutputs.TXOutputs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return org.tron.protos.core.TronTXOutputs.internal_static_protos_TXOutputs_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return org.tron.protos.core.TronTXOutputs.internal_static_protos_TXOutputs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tron.protos.core.TronTXOutputs.TXOutputs.class, org.tron.protos.core.TronTXOutputs.TXOutputs.Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
            .alwaysUseFieldBuilders) {
          getOutputsFieldBuilder();
        }
      }

      public Builder clear() {
        super.clear();
        if (outputsBuilder_ == null) {
          outputs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          outputsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return org.tron.protos.core.TronTXOutputs.internal_static_protos_TXOutputs_descriptor;
      }

      public org.tron.protos.core.TronTXOutputs.TXOutputs getDefaultInstanceForType() {
        return org.tron.protos.core.TronTXOutputs.TXOutputs.getDefaultInstance();
      }

      public org.tron.protos.core.TronTXOutputs.TXOutputs build() {
        org.tron.protos.core.TronTXOutputs.TXOutputs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tron.protos.core.TronTXOutputs.TXOutputs buildPartial() {
        org.tron.protos.core.TronTXOutputs.TXOutputs result = new org.tron.protos.core.TronTXOutputs.TXOutputs(this);
        int from_bitField0_ = bitField0_;
        if (outputsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            outputs_ = java.util.Collections.unmodifiableList(outputs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.outputs_ = outputs_;
        } else {
          result.outputs_ = outputsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tron.protos.core.TronTXOutputs.TXOutputs) {
          return mergeFrom((org.tron.protos.core.TronTXOutputs.TXOutputs) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tron.protos.core.TronTXOutputs.TXOutputs other) {
        if (other == org.tron.protos.core.TronTXOutputs.TXOutputs.getDefaultInstance()) {
          return this;
        }
        if (outputsBuilder_ == null) {
          if (!other.outputs_.isEmpty()) {
            if (outputs_.isEmpty()) {
              outputs_ = other.outputs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOutputsIsMutable();
              outputs_.addAll(other.outputs_);
            }
            onChanged();
          }
        } else {
          if (!other.outputs_.isEmpty()) {
            if (outputsBuilder_.isEmpty()) {
              outputsBuilder_.dispose();
              outputsBuilder_ = null;
              outputs_ = other.outputs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              outputsBuilder_ =
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                      getOutputsFieldBuilder() : null;
            } else {
              outputsBuilder_.addAllMessages(other.outputs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tron.protos.core.TronTXOutputs.TXOutputs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tron.protos.core.TronTXOutputs.TXOutputs) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private void ensureOutputsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          outputs_ = new java.util.ArrayList<org.tron.protos.core.TronTXOutput.TXOutput>(outputs_);
          bitField0_ |= 0x00000001;
        }
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public java.util.List<org.tron.protos.core.TronTXOutput.TXOutput> getOutputsList() {
        if (outputsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(outputs_);
        } else {
          return outputsBuilder_.getMessageList();
        }
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public int getOutputsCount() {
        if (outputsBuilder_ == null) {
          return outputs_.size();
        } else {
          return outputsBuilder_.getCount();
        }
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public org.tron.protos.core.TronTXOutput.TXOutput getOutputs(int index) {
        if (outputsBuilder_ == null) {
          return outputs_.get(index);
        } else {
          return outputsBuilder_.getMessage(index);
        }
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public Builder setOutputs(
          int index, org.tron.protos.core.TronTXOutput.TXOutput value) {
        if (outputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOutputsIsMutable();
          outputs_.set(index, value);
          onChanged();
        } else {
          outputsBuilder_.setMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public Builder setOutputs(
          int index, org.tron.protos.core.TronTXOutput.TXOutput.Builder builderForValue) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          outputs_.set(index, builderForValue.build());
          onChanged();
        } else {
          outputsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public Builder addOutputs(org.tron.protos.core.TronTXOutput.TXOutput value) {
        if (outputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOutputsIsMutable();
          outputs_.add(value);
          onChanged();
        } else {
          outputsBuilder_.addMessage(value);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public Builder addOutputs(
          int index, org.tron.protos.core.TronTXOutput.TXOutput value) {
        if (outputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOutputsIsMutable();
          outputs_.add(index, value);
          onChanged();
        } else {
          outputsBuilder_.addMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public Builder addOutputs(
          org.tron.protos.core.TronTXOutput.TXOutput.Builder builderForValue) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          outputs_.add(builderForValue.build());
          onChanged();
        } else {
          outputsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public Builder addOutputs(
          int index, org.tron.protos.core.TronTXOutput.TXOutput.Builder builderForValue) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          outputs_.add(index, builderForValue.build());
          onChanged();
        } else {
          outputsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public Builder addAllOutputs(
          java.lang.Iterable<? extends org.tron.protos.core.TronTXOutput.TXOutput> values) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, outputs_);
          onChanged();
        } else {
          outputsBuilder_.addAllMessages(values);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public Builder clearOutputs() {
        if (outputsBuilder_ == null) {
          outputs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          outputsBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public Builder removeOutputs(int index) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          outputs_.remove(index);
          onChanged();
        } else {
          outputsBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public org.tron.protos.core.TronTXOutput.TXOutput.Builder getOutputsBuilder(
          int index) {
        return getOutputsFieldBuilder().getBuilder(index);
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public org.tron.protos.core.TronTXOutput.TXOutputOrBuilder getOutputsOrBuilder(
          int index) {
        if (outputsBuilder_ == null) {
          return outputs_.get(index);
        } else {
          return outputsBuilder_.getMessageOrBuilder(index);
        }
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public java.util.List<? extends org.tron.protos.core.TronTXOutput.TXOutputOrBuilder>
      getOutputsOrBuilderList() {
        if (outputsBuilder_ != null) {
          return outputsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(outputs_);
        }
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public org.tron.protos.core.TronTXOutput.TXOutput.Builder addOutputsBuilder() {
        return getOutputsFieldBuilder().addBuilder(
            org.tron.protos.core.TronTXOutput.TXOutput.getDefaultInstance());
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public org.tron.protos.core.TronTXOutput.TXOutput.Builder addOutputsBuilder(
          int index) {
        return getOutputsFieldBuilder().addBuilder(
            index, org.tron.protos.core.TronTXOutput.TXOutput.getDefaultInstance());
      }

      /**
       * <code>repeated .protos.TXOutput outputs = 1;</code>
       */
      public java.util.List<org.tron.protos.core.TronTXOutput.TXOutput.Builder>
      getOutputsBuilderList() {
        return getOutputsFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.tron.protos.core.TronTXOutput.TXOutput, org.tron.protos.core.TronTXOutput.TXOutput.Builder, org.tron.protos.core.TronTXOutput.TXOutputOrBuilder>
      getOutputsFieldBuilder() {
        if (outputsBuilder_ == null) {
          outputsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.tron.protos.core.TronTXOutput.TXOutput, org.tron.protos.core.TronTXOutput.TXOutput.Builder, org.tron.protos.core.TronTXOutput.TXOutputOrBuilder>(
              outputs_,
              ((bitField0_ & 0x00000001) == 0x00000001),
              getParentForChildren(),
              isClean());
          outputs_ = null;
        }
        return outputsBuilder_;
      }

      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.TXOutputs)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
