// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/TronTransaction.proto

package org.tron.protos.core;

public final class TronTransaction {
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_protos_Transaction_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_Transaction_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
        "\n\032core/TronTransaction.proto\022\006protos\032\026co" +
            "re/TronTXInput.proto\032\027core/TronTXOutput." +
            "proto\"W\n\013Transaction\022\n\n\002id\030\001 \001(\014\022\034\n\003vin\030" +
            "\002 \003(\0132\017.protos.TXInput\022\036\n\004vout\030\003 \003(\0132\020.p" +
            "rotos.TXOutputB\'\n\024org.tron.protos.coreB\017" +
            "TronTransactionb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
                org.tron.protos.core.TronTXInput.getDescriptor(),
                org.tron.protos.core.TronTXOutput.getDescriptor(),
            }, assigner);
    internal_static_protos_Transaction_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_protos_Transaction_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_Transaction_descriptor,
        new java.lang.String[] {"Id", "Vin", "Vout",});
    org.tron.protos.core.TronTXInput.getDescriptor();
    org.tron.protos.core.TronTXOutput.getDescriptor();
  }

  private TronTransaction() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.Transaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes id = 1;</code>
     */
    com.google.protobuf.ByteString getId();

    /**
     * <code>repeated .protos.TXInput vin = 2;</code>
     */
    java.util.List<org.tron.protos.core.TronTXInput.TXInput>
    getVinList();

    /**
     * <code>repeated .protos.TXInput vin = 2;</code>
     */
    org.tron.protos.core.TronTXInput.TXInput getVin(int index);

    /**
     * <code>repeated .protos.TXInput vin = 2;</code>
     */
    int getVinCount();

    /**
     * <code>repeated .protos.TXInput vin = 2;</code>
     */
    java.util.List<? extends org.tron.protos.core.TronTXInput.TXInputOrBuilder>
    getVinOrBuilderList();

    /**
     * <code>repeated .protos.TXInput vin = 2;</code>
     */
    org.tron.protos.core.TronTXInput.TXInputOrBuilder getVinOrBuilder(
        int index);

    /**
     * <code>repeated .protos.TXOutput vout = 3;</code>
     */
    java.util.List<org.tron.protos.core.TronTXOutput.TXOutput>
    getVoutList();

    /**
     * <code>repeated .protos.TXOutput vout = 3;</code>
     */
    org.tron.protos.core.TronTXOutput.TXOutput getVout(int index);

    /**
     * <code>repeated .protos.TXOutput vout = 3;</code>
     */
    int getVoutCount();

    /**
     * <code>repeated .protos.TXOutput vout = 3;</code>
     */
    java.util.List<? extends org.tron.protos.core.TronTXOutput.TXOutputOrBuilder>
    getVoutOrBuilderList();

    /**
     * <code>repeated .protos.TXOutput vout = 3;</code>
     */
    org.tron.protos.core.TronTXOutput.TXOutputOrBuilder getVoutOrBuilder(
        int index);
  }

  /**
   * Protobuf type {@code protos.Transaction}
   */
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.Transaction)
      TransactionOrBuilder {
    public static final int ID_FIELD_NUMBER = 1;
    public static final int VIN_FIELD_NUMBER = 2;
    public static final int VOUT_FIELD_NUMBER = 3;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:protos.Transaction)
    private static final org.tron.protos.core.TronTransaction.Transaction DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Transaction>
        PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    static {
      DEFAULT_INSTANCE = new org.tron.protos.core.TronTransaction.Transaction();
    }

    private int bitField0_;
    private com.google.protobuf.ByteString id_;
    private java.util.List<org.tron.protos.core.TronTXInput.TXInput> vin_;
    private java.util.List<org.tron.protos.core.TronTXOutput.TXOutput> vout_;
    private byte memoizedIsInitialized = -1;

    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Transaction() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      vin_ = java.util.Collections.emptyList();
      vout_ = java.util.Collections.emptyList();
    }

    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              id_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                vin_ = new java.util.ArrayList<org.tron.protos.core.TronTXInput.TXInput>();
                mutable_bitField0_ |= 0x00000002;
              }
              vin_.add(
                  input.readMessage(org.tron.protos.core.TronTXInput.TXInput.parser(),
                      extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                vout_ = new java.util.ArrayList<org.tron.protos.core.TronTXOutput.TXOutput>();
                mutable_bitField0_ |= 0x00000004;
              }
              vout_.add(
                  input.readMessage(org.tron.protos.core.TronTXOutput.TXOutput.parser(),
                      extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          vin_ = java.util.Collections.unmodifiableList(vin_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          vout_ = java.util.Collections.unmodifiableList(vout_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return org.tron.protos.core.TronTransaction.internal_static_protos_Transaction_descriptor;
    }

    public static org.tron.protos.core.TronTransaction.Transaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.tron.protos.core.TronTransaction.Transaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tron.protos.core.TronTransaction.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.tron.protos.core.TronTransaction.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tron.protos.core.TronTransaction.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.tron.protos.core.TronTransaction.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tron.protos.core.TronTransaction.Transaction parseFrom(
        java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static org.tron.protos.core.TronTransaction.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.tron.protos.core.TronTransaction.Transaction parseDelimitedFrom(
        java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.tron.protos.core.TronTransaction.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.tron.protos.core.TronTransaction.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static org.tron.protos.core.TronTransaction.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.tron.protos.core.TronTransaction.Transaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static org.tron.protos.core.TronTransaction.Transaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<Transaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return org.tron.protos.core.TronTransaction.internal_static_protos_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tron.protos.core.TronTransaction.Transaction.class,
              org.tron.protos.core.TronTransaction.Transaction.Builder.class);
    }

    /**
     * <code>bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    /**
     * <code>repeated .protos.TXInput vin = 2;</code>
     */
    public java.util.List<org.tron.protos.core.TronTXInput.TXInput> getVinList() {
      return vin_;
    }

    /**
     * <code>repeated .protos.TXInput vin = 2;</code>
     */
    public java.util.List<? extends org.tron.protos.core.TronTXInput.TXInputOrBuilder>
    getVinOrBuilderList() {
      return vin_;
    }

    /**
     * <code>repeated .protos.TXInput vin = 2;</code>
     */
    public int getVinCount() {
      return vin_.size();
    }

    /**
     * <code>repeated .protos.TXInput vin = 2;</code>
     */
    public org.tron.protos.core.TronTXInput.TXInput getVin(int index) {
      return vin_.get(index);
    }

    /**
     * <code>repeated .protos.TXInput vin = 2;</code>
     */
    public org.tron.protos.core.TronTXInput.TXInputOrBuilder getVinOrBuilder(
        int index) {
      return vin_.get(index);
    }

    /**
     * <code>repeated .protos.TXOutput vout = 3;</code>
     */
    public java.util.List<org.tron.protos.core.TronTXOutput.TXOutput> getVoutList() {
      return vout_;
    }

    /**
     * <code>repeated .protos.TXOutput vout = 3;</code>
     */
    public java.util.List<? extends org.tron.protos.core.TronTXOutput.TXOutputOrBuilder>
    getVoutOrBuilderList() {
      return vout_;
    }

    /**
     * <code>repeated .protos.TXOutput vout = 3;</code>
     */
    public int getVoutCount() {
      return vout_.size();
    }

    /**
     * <code>repeated .protos.TXOutput vout = 3;</code>
     */
    public org.tron.protos.core.TronTXOutput.TXOutput getVout(int index) {
      return vout_.get(index);
    }

    /**
     * <code>repeated .protos.TXOutput vout = 3;</code>
     */
    public org.tron.protos.core.TronTXOutput.TXOutputOrBuilder getVoutOrBuilder(
        int index) {
      return vout_.get(index);
    }

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      if (!id_.isEmpty()) {
        output.writeBytes(1, id_);
      }
      for (int i = 0; i < vin_.size(); i++) {
        output.writeMessage(2, vin_.get(i));
      }
      for (int i = 0; i < vout_.size(); i++) {
        output.writeMessage(3, vout_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
        return size;
      }

      size = 0;
      if (!id_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, id_);
      }
      for (int i = 0; i < vin_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, vin_.get(i));
      }
      for (int i = 0; i < vout_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, vout_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof org.tron.protos.core.TronTransaction.Transaction)) {
        return super.equals(obj);
      }
      org.tron.protos.core.TronTransaction.Transaction other = (org.tron.protos.core.TronTransaction.Transaction) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getVinList()
          .equals(other.getVinList());
      result = result && getVoutList()
          .equals(other.getVoutList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (getVinCount() > 0) {
        hash = (37 * hash) + VIN_FIELD_NUMBER;
        hash = (53 * hash) + getVinList().hashCode();
      }
      if (getVoutCount() > 0) {
        hash = (37 * hash) + VOUT_FIELD_NUMBER;
        hash = (53 * hash) + getVoutList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    public org.tron.protos.core.TronTransaction.Transaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code protos.Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.Transaction)
        org.tron.protos.core.TronTransaction.TransactionOrBuilder {
      private int bitField0_;
      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      private java.util.List<org.tron.protos.core.TronTXInput.TXInput> vin_ =
          java.util.Collections.emptyList();
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.tron.protos.core.TronTXInput.TXInput, org.tron.protos.core.TronTXInput.TXInput.Builder, org.tron.protos.core.TronTXInput.TXInputOrBuilder> vinBuilder_;
      private java.util.List<org.tron.protos.core.TronTXOutput.TXOutput> vout_ =
          java.util.Collections.emptyList();
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.tron.protos.core.TronTXOutput.TXOutput, org.tron.protos.core.TronTXOutput.TXOutput.Builder, org.tron.protos.core.TronTXOutput.TXOutputOrBuilder> voutBuilder_;

      // Construct using org.tron.protos.core.TronTransaction.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return org.tron.protos.core.TronTransaction.internal_static_protos_Transaction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return org.tron.protos.core.TronTransaction.internal_static_protos_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tron.protos.core.TronTransaction.Transaction.class,
                org.tron.protos.core.TronTransaction.Transaction.Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
            .alwaysUseFieldBuilders) {
          getVinFieldBuilder();
          getVoutFieldBuilder();
        }
      }

      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;

        if (vinBuilder_ == null) {
          vin_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          vinBuilder_.clear();
        }
        if (voutBuilder_ == null) {
          vout_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          voutBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return org.tron.protos.core.TronTransaction.internal_static_protos_Transaction_descriptor;
      }

      public org.tron.protos.core.TronTransaction.Transaction getDefaultInstanceForType() {
        return org.tron.protos.core.TronTransaction.Transaction.getDefaultInstance();
      }

      public org.tron.protos.core.TronTransaction.Transaction build() {
        org.tron.protos.core.TronTransaction.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tron.protos.core.TronTransaction.Transaction buildPartial() {
        org.tron.protos.core.TronTransaction.Transaction result = new org.tron.protos.core.TronTransaction.Transaction(
            this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        if (vinBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            vin_ = java.util.Collections.unmodifiableList(vin_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.vin_ = vin_;
        } else {
          result.vin_ = vinBuilder_.build();
        }
        if (voutBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            vout_ = java.util.Collections.unmodifiableList(vout_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.vout_ = vout_;
        } else {
          result.vout_ = voutBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tron.protos.core.TronTransaction.Transaction) {
          return mergeFrom((org.tron.protos.core.TronTransaction.Transaction) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tron.protos.core.TronTransaction.Transaction other) {
        if (other == org.tron.protos.core.TronTransaction.Transaction.getDefaultInstance()) {
          return this;
        }
        if (other.getId() != com.google.protobuf.ByteString.EMPTY) {
          setId(other.getId());
        }
        if (vinBuilder_ == null) {
          if (!other.vin_.isEmpty()) {
            if (vin_.isEmpty()) {
              vin_ = other.vin_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureVinIsMutable();
              vin_.addAll(other.vin_);
            }
            onChanged();
          }
        } else {
          if (!other.vin_.isEmpty()) {
            if (vinBuilder_.isEmpty()) {
              vinBuilder_.dispose();
              vinBuilder_ = null;
              vin_ = other.vin_;
              bitField0_ = (bitField0_ & ~0x00000002);
              vinBuilder_ =
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                      getVinFieldBuilder() : null;
            } else {
              vinBuilder_.addAllMessages(other.vin_);
            }
          }
        }
        if (voutBuilder_ == null) {
          if (!other.vout_.isEmpty()) {
            if (vout_.isEmpty()) {
              vout_ = other.vout_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureVoutIsMutable();
              vout_.addAll(other.vout_);
            }
            onChanged();
          }
        } else {
          if (!other.vout_.isEmpty()) {
            if (voutBuilder_.isEmpty()) {
              voutBuilder_.dispose();
              voutBuilder_ = null;
              vout_ = other.vout_;
              bitField0_ = (bitField0_ & ~0x00000004);
              voutBuilder_ =
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                      getVoutFieldBuilder() : null;
            } else {
              voutBuilder_.addAllMessages(other.vout_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tron.protos.core.TronTransaction.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tron.protos.core.TronTransaction.Transaction) e
              .getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>bytes id = 1;</code>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }

      /**
       * <code>bytes id = 1;</code>
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        id_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bytes id = 1;</code>
       */
      public Builder clearId() {

        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      private void ensureVinIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          vin_ = new java.util.ArrayList<org.tron.protos.core.TronTXInput.TXInput>(vin_);
          bitField0_ |= 0x00000002;
        }
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public java.util.List<org.tron.protos.core.TronTXInput.TXInput> getVinList() {
        if (vinBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vin_);
        } else {
          return vinBuilder_.getMessageList();
        }
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public int getVinCount() {
        if (vinBuilder_ == null) {
          return vin_.size();
        } else {
          return vinBuilder_.getCount();
        }
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public org.tron.protos.core.TronTXInput.TXInput getVin(int index) {
        if (vinBuilder_ == null) {
          return vin_.get(index);
        } else {
          return vinBuilder_.getMessage(index);
        }
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public Builder setVin(
          int index, org.tron.protos.core.TronTXInput.TXInput value) {
        if (vinBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVinIsMutable();
          vin_.set(index, value);
          onChanged();
        } else {
          vinBuilder_.setMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public Builder setVin(
          int index, org.tron.protos.core.TronTXInput.TXInput.Builder builderForValue) {
        if (vinBuilder_ == null) {
          ensureVinIsMutable();
          vin_.set(index, builderForValue.build());
          onChanged();
        } else {
          vinBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public Builder addVin(org.tron.protos.core.TronTXInput.TXInput value) {
        if (vinBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVinIsMutable();
          vin_.add(value);
          onChanged();
        } else {
          vinBuilder_.addMessage(value);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public Builder addVin(
          int index, org.tron.protos.core.TronTXInput.TXInput value) {
        if (vinBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVinIsMutable();
          vin_.add(index, value);
          onChanged();
        } else {
          vinBuilder_.addMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public Builder addVin(
          org.tron.protos.core.TronTXInput.TXInput.Builder builderForValue) {
        if (vinBuilder_ == null) {
          ensureVinIsMutable();
          vin_.add(builderForValue.build());
          onChanged();
        } else {
          vinBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public Builder addVin(
          int index, org.tron.protos.core.TronTXInput.TXInput.Builder builderForValue) {
        if (vinBuilder_ == null) {
          ensureVinIsMutable();
          vin_.add(index, builderForValue.build());
          onChanged();
        } else {
          vinBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public Builder addAllVin(
          java.lang.Iterable<? extends org.tron.protos.core.TronTXInput.TXInput> values) {
        if (vinBuilder_ == null) {
          ensureVinIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, vin_);
          onChanged();
        } else {
          vinBuilder_.addAllMessages(values);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public Builder clearVin() {
        if (vinBuilder_ == null) {
          vin_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          vinBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public Builder removeVin(int index) {
        if (vinBuilder_ == null) {
          ensureVinIsMutable();
          vin_.remove(index);
          onChanged();
        } else {
          vinBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public org.tron.protos.core.TronTXInput.TXInput.Builder getVinBuilder(
          int index) {
        return getVinFieldBuilder().getBuilder(index);
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public org.tron.protos.core.TronTXInput.TXInputOrBuilder getVinOrBuilder(
          int index) {
        if (vinBuilder_ == null) {
          return vin_.get(index);
        } else {
          return vinBuilder_.getMessageOrBuilder(index);
        }
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public java.util.List<? extends org.tron.protos.core.TronTXInput.TXInputOrBuilder>
      getVinOrBuilderList() {
        if (vinBuilder_ != null) {
          return vinBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vin_);
        }
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public org.tron.protos.core.TronTXInput.TXInput.Builder addVinBuilder() {
        return getVinFieldBuilder().addBuilder(
            org.tron.protos.core.TronTXInput.TXInput.getDefaultInstance());
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public org.tron.protos.core.TronTXInput.TXInput.Builder addVinBuilder(
          int index) {
        return getVinFieldBuilder().addBuilder(
            index, org.tron.protos.core.TronTXInput.TXInput.getDefaultInstance());
      }

      /**
       * <code>repeated .protos.TXInput vin = 2;</code>
       */
      public java.util.List<org.tron.protos.core.TronTXInput.TXInput.Builder>
      getVinBuilderList() {
        return getVinFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.tron.protos.core.TronTXInput.TXInput, org.tron.protos.core.TronTXInput.TXInput.Builder, org.tron.protos.core.TronTXInput.TXInputOrBuilder>
      getVinFieldBuilder() {
        if (vinBuilder_ == null) {
          vinBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.tron.protos.core.TronTXInput.TXInput, org.tron.protos.core.TronTXInput.TXInput.Builder, org.tron.protos.core.TronTXInput.TXInputOrBuilder>(
              vin_,
              ((bitField0_ & 0x00000002) == 0x00000002),
              getParentForChildren(),
              isClean());
          vin_ = null;
        }
        return vinBuilder_;
      }

      private void ensureVoutIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          vout_ = new java.util.ArrayList<org.tron.protos.core.TronTXOutput.TXOutput>(vout_);
          bitField0_ |= 0x00000004;
        }
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public java.util.List<org.tron.protos.core.TronTXOutput.TXOutput> getVoutList() {
        if (voutBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vout_);
        } else {
          return voutBuilder_.getMessageList();
        }
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public int getVoutCount() {
        if (voutBuilder_ == null) {
          return vout_.size();
        } else {
          return voutBuilder_.getCount();
        }
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public org.tron.protos.core.TronTXOutput.TXOutput getVout(int index) {
        if (voutBuilder_ == null) {
          return vout_.get(index);
        } else {
          return voutBuilder_.getMessage(index);
        }
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public Builder setVout(
          int index, org.tron.protos.core.TronTXOutput.TXOutput value) {
        if (voutBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVoutIsMutable();
          vout_.set(index, value);
          onChanged();
        } else {
          voutBuilder_.setMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public Builder setVout(
          int index, org.tron.protos.core.TronTXOutput.TXOutput.Builder builderForValue) {
        if (voutBuilder_ == null) {
          ensureVoutIsMutable();
          vout_.set(index, builderForValue.build());
          onChanged();
        } else {
          voutBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public Builder addVout(org.tron.protos.core.TronTXOutput.TXOutput value) {
        if (voutBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVoutIsMutable();
          vout_.add(value);
          onChanged();
        } else {
          voutBuilder_.addMessage(value);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public Builder addVout(
          int index, org.tron.protos.core.TronTXOutput.TXOutput value) {
        if (voutBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVoutIsMutable();
          vout_.add(index, value);
          onChanged();
        } else {
          voutBuilder_.addMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public Builder addVout(
          org.tron.protos.core.TronTXOutput.TXOutput.Builder builderForValue) {
        if (voutBuilder_ == null) {
          ensureVoutIsMutable();
          vout_.add(builderForValue.build());
          onChanged();
        } else {
          voutBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public Builder addVout(
          int index, org.tron.protos.core.TronTXOutput.TXOutput.Builder builderForValue) {
        if (voutBuilder_ == null) {
          ensureVoutIsMutable();
          vout_.add(index, builderForValue.build());
          onChanged();
        } else {
          voutBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public Builder addAllVout(
          java.lang.Iterable<? extends org.tron.protos.core.TronTXOutput.TXOutput> values) {
        if (voutBuilder_ == null) {
          ensureVoutIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, vout_);
          onChanged();
        } else {
          voutBuilder_.addAllMessages(values);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public Builder clearVout() {
        if (voutBuilder_ == null) {
          vout_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          voutBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public Builder removeVout(int index) {
        if (voutBuilder_ == null) {
          ensureVoutIsMutable();
          vout_.remove(index);
          onChanged();
        } else {
          voutBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public org.tron.protos.core.TronTXOutput.TXOutput.Builder getVoutBuilder(
          int index) {
        return getVoutFieldBuilder().getBuilder(index);
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public org.tron.protos.core.TronTXOutput.TXOutputOrBuilder getVoutOrBuilder(
          int index) {
        if (voutBuilder_ == null) {
          return vout_.get(index);
        } else {
          return voutBuilder_.getMessageOrBuilder(index);
        }
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public java.util.List<? extends org.tron.protos.core.TronTXOutput.TXOutputOrBuilder>
      getVoutOrBuilderList() {
        if (voutBuilder_ != null) {
          return voutBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vout_);
        }
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public org.tron.protos.core.TronTXOutput.TXOutput.Builder addVoutBuilder() {
        return getVoutFieldBuilder().addBuilder(
            org.tron.protos.core.TronTXOutput.TXOutput.getDefaultInstance());
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public org.tron.protos.core.TronTXOutput.TXOutput.Builder addVoutBuilder(
          int index) {
        return getVoutFieldBuilder().addBuilder(
            index, org.tron.protos.core.TronTXOutput.TXOutput.getDefaultInstance());
      }

      /**
       * <code>repeated .protos.TXOutput vout = 3;</code>
       */
      public java.util.List<org.tron.protos.core.TronTXOutput.TXOutput.Builder>
      getVoutBuilderList() {
        return getVoutFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.tron.protos.core.TronTXOutput.TXOutput, org.tron.protos.core.TronTXOutput.TXOutput.Builder, org.tron.protos.core.TronTXOutput.TXOutputOrBuilder>
      getVoutFieldBuilder() {
        if (voutBuilder_ == null) {
          voutBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.tron.protos.core.TronTXOutput.TXOutput, org.tron.protos.core.TronTXOutput.TXOutput.Builder, org.tron.protos.core.TronTXOutput.TXOutputOrBuilder>(
              vout_,
              ((bitField0_ & 0x00000004) == 0x00000004),
              getParentForChildren(),
              isClean());
          vout_ = null;
        }
        return voutBuilder_;
      }

      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.Transaction)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
