kind: ReplicationController
apiVersion: v1
metadata:
  name: kafka-controller
spec:
  replicas: 1
  selector:
    app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zook:2181
        - name: KAFKA_CREATE_TOPICS
          value: "block:1:1,transaction:1:1" 
      - name: zookeeper
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181