name: Coverage Build

on:
  pull_request:
    branches: [ 'develop', 'release_**' ]
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-coverage:
    name: Build ubuntu24 (JDK 8 / x86_64)
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Check Java version
        run: java -version

      - name: Stop Gradle daemon
        run: ./gradlew --stop || true

      - name: Build
        run: ./gradlew clean build --no-daemon --no-build-cache --parallel

      - name: Generate JaCoCo report
        run: ./gradlew jacocoTestReport  --no-daemon --no-build-cache

      - name: Upload JaCoCo artifact
        uses: actions/upload-artifact@v6
        with:
          name: jacoco-coverage
          path: |
            actuator/build/reports/jacoco/test/jacocoTestReport.xml
            chainbase/build/reports/jacoco/test/jacocoTestReport.xml
            common/build/reports/jacoco/test/jacocoTestReport.xml
            consensus/build/reports/jacoco/test/jacocoTestReport.xml
            crypto/build/reports/jacoco/test/jacocoTestReport.xml
            framework/build/reports/jacoco/test/jacocoTestReport.xml
            plugins/build/reports/jacoco/test/jacocoTestReport.xml
          if-no-files-found: error
